server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: user-account-service
          uri: lb://user-account-service/
          predicates:
            - Path=/accounts/**
        - id: game-service
          uri: lb://game-service/
          predicates:
            - Path=/game/**
        - id: game-list-service
          uri: lb://game-list-service/
          predicates:
            - Path=/list/**
        - id: notification-service
          uri: lb://notification-service/
          predicates:
            - Path=/notification/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8085/realms/gdw/protocol/openid-connect/certs"
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0