server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://zipkin:9411


management:
  endpoint:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
